tjdests/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

"""tjdests URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

from destinations import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^accounts/login/$', views.login_view),
    url(r'^register$', views.register_view, name='register'),
    url(r'^verify/(?P<verify_key>[\w-]+)?$', views.verify_view, name='verify'),
    url(r'^update$', views.update_view, name='update'),

    url(r'^update/schools$', views.update_schools_view, name='update_schools'),
    url(r'^update_school$', views.update_school_view, name='update_school'),
    url(r'^update_school/(?P<app_id>\d+)?$', views.update_school_view, name='update_school'),

    url(r'^update/apexams$', views.update_apexams_view, name='update_apexams'),
    url(r'^update_apexam$', views.update_apexam_view, name='update_apexam'),
    url(r'^update_apexam/(?P<exam_id>\d+)?$', views.update_apexam_view, name='update_apexam'),

    url(r'^update/sat2s$', views.update_sat2s_view, name='update_sat2s'),
    url(r'^update_sat2$', views.update_sat2_view, name='update_sat2'),
    url(r'^update_sat2/(?P<exam_id>\d+)?$', views.update_sat2_view, name='update_sat2'),
    

    url(r'^students$', views.students_view, name='students'),
    url(r'^colleges$', views.colleges_view, name='colleges'),
    url(r'^destinations$', views.destinations_view, name='destinations'),
    url(r'^student/(?P<student_id>\d+)?$', views.student_view, name='student'),
    url(r'^college/(?P<college_ceeb>\d+)?$', views.college_view, name='college'),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
]


handler503 = 'destinations.views.maintenance_mode'

tjdests/destinations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core import exceptions
from django.db import models

class College(models.Model):
    name = models.CharField(max_length=1000)
    ceeb = models.IntegerField(unique=True)

    def __unicode__(self):
        return "{}: {}".format(self.ceeb, self.name)

    @property
    def applied_set(self):
        return self.collegeapp_set.all()

    @property
    def attending_set(self):
        return self.collegeapp_set.filter(attending=True)

    @property
    def accepted_set(self):
        return self.collegeapp_set.filter(result="AC")

    @property
    def rejected_set(self):
        return self.collegeapp_set.filter(result="RJ")

    @property
    def waitlisted_set(self):
        return self.collegeapp_set.filter(waitlisted=True)

    class Meta:
        ordering = ["name"]


class CollegeApp(models.Model):
    college = models.ForeignKey("College")
    program = models.CharField(max_length=250)
    senior = models.ForeignKey("Senior")
    attending = models.BooleanField()
    TYPES = (
        ("RD", "Regular Decision"),
        ("ED", "Early Decision"),
        ("EA", "Early Action"),
        ("PR", "Priority"),
        ("RL", "Rolling Admission")
    )
    applied = models.CharField(max_length=2, choices=TYPES, default="RD")
    RESULTS = (
        ("NA", "Applied"),
        ("AC", "Accepted"),
        ("RJ", "Rejected")
    )
    result = models.CharField(max_length=2, choices=RESULTS, default="NA")
    submitted = models.DateField(null=True, blank=True)
    notified = models.DateField(null=True, blank=True)
    legacy = models.BooleanField(default=False)
    interview = models.BooleanField(default=False)
    deferred = models.BooleanField(default=False)
    waitlisted = models.BooleanField(default=False)
    recruited = models.CharField(max_length=100, blank=True)
    supplement = models.CharField(max_length=100, blank=True)
    comments = models.CharField(max_length=1000, blank=True)

    @property
    def applied_name(self):
        types = {i[0]: i[1] for i in self.TYPES}
        return types[self.applied] if self.applied in types else ""

    @property
    def result_name(self):
        results = {i[0]: i[1] for i in self.RESULTS}
        return results[self.result] if self.result in results else ""
    
    
    

    def __unicode__(self):
        return "{}".format(self.college)


class APExam(models.Model):
    EXAMS = ("Art History",
             "Music Theory",
             "Studio Art 2D",
             "Studio Art 3D",
             "Studio Art Drawing",
             "English Language",
             "English Literature",
             "Comparative Govt",
             "European History",
             "Human Geography",
             "Macroeconomics",
             "Microeconomics",
             "Psychology",
             "US Government/Politics",
             "US History",
             "World History",
             "Calculus AB",
             "Calculus BC",
             "Computer Science A",
             #"CS Principles",
             "Statistics",
             "Biology",
             "Chemistry",
             "Environmental Science",
             "Physics C E&M",
             "Physics C Mech",
             "Physics 1",
             "Physics 2",
             "Chinese",
             "French",
             "German",
             "Italian",
             "Japanese",
             "Latin",
             "Spanish Lang",
             "Spanish Lit")
    name = models.CharField(max_length=100, choices=[(i, i) for i in EXAMS])
    senior = models.ForeignKey("Senior")
    score = models.IntegerField()
    year = models.IntegerField()
    took_class = models.BooleanField(default=True)

    def __unicode__(self):
        return "{} ({})".format(self.name, self.score)


class SAT2(models.Model):
    EXAMS = ("Literature",
             "US History",
             "World History",
             "Math Level 1",
             "Math Level 2",
             "Biology/EM",
             "Chemistry",
             "Physics",
             "French",
             "French Listening",
             "German",
             "German Listening",
             "Spanish",
             "Spanish Listening",
             "Modern Hebrew",
             "Italian",
             "Latin",
             "Chinese Listening",
             "Japanese Listening",
             "Korean Listening")
    name = models.CharField(max_length=100, choices=[(i, i) for i in EXAMS])
    senior = models.ForeignKey("Senior")
    score = models.IntegerField()
    year = models.IntegerField()

    def __unicode__(self):
        return "{} ({})".format(self.name, self.score)

class UserManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        user = self.model(username=username, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **kwargs):
        user = self.model(username=username, is_staff=True, is_superuser=True, **kwargs)
        user.set_password(password)
        user.save()
        return user

class User(AbstractBaseUser):
    objects = UserManager()

    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    senior = models.OneToOneField("Senior", null=True)
    verified = models.BooleanField(default=False)
    verify_key = models.CharField(max_length=50, null=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"

    def get_full_name(self):
        return "{} ({})".format(self.name, self.username)

    def get_short_name(self):
        return self.name

    @property
    def is_superuser(self):
        return self.is_admin

    @property
    def is_admin(self):
        return self.is_staff

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    @property
    def name(self):
        return "{} {}".format(self.first_name, self.last_name)

    @property
    def is_senior(self):
        return self.username.startswith('2016')
    
    

    def __unicode__(self):
        return "{} {} ({})".format(self.first_name, self.last_name, self.username)

    class Meta:
        ordering = ["last_name", "first_name"]

class Senior(models.Model):
    email = models.CharField(max_length=100, blank=True)
    gender = models.CharField(max_length=1, choices=(("M", "Male"), ("F", "Female")))
    RACES = [(i, i) for i in (
        "White",
        "Asian",
        "Black",
        "Hispanic",
        "Indian/AK Native",
        "Multiracial"
    )]
    race = models.CharField(max_length=20, choices=RACES)
    hispanic = models.BooleanField()
    international = models.BooleanField()

    gpa = models.DecimalField(max_digits=4, decimal_places=3, default=0.00)
    sat2400 = models.IntegerField(default=0)
    sat1600 = models.IntegerField(default=0)
    act = models.IntegerField(default=0)
    honors = models.CharField(max_length=1000, blank=True)

    colleges = models.ManyToManyField("College", through="CollegeApp")

    @property
    def attending_college(self):
        att = self.collegeapp_set.filter(attending=True)
        if att:
            return att[0]
        return None

    @property
    def sat(self):
        return self.sat2400 if self.sat2400 else self.sat1600

    def __unicode__(self):
        try:
            return "{}".format(self.user)
        except Exception:
            return "{}".format(self.email)

tjdests/destinations/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import uuid
from captcha.fields import CaptchaField
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import College, CollegeApp, APExam, SAT2, Senior, User

class CollegeForm(forms.ModelForm):

    class Meta:
        model = College
        fields = ["name",
                  "ceeb"]

class CollegeAppForm(forms.ModelForm):
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(CollegeAppForm, self).__init__(*args, **kwargs)
        self.fields["college"].help_text = "Click in the field to search by school name or College Board CEEB number"

    class Meta:
        model = CollegeApp
        fields = ["college",
                  "program",
                  "applied",
                  "submitted",
                  "notified",
                  "result",
                  "attending",
                  "legacy",
                  "interview",
                  "deferred",
                  "waitlisted",
                  "recruited",
                  "supplement",
                  "comments"]

class APExamForm(forms.ModelForm):
    score = forms.IntegerField(max_value=5, min_value=1, widget=forms.NumberInput(attrs={"max": 5, "min": 1, "placeholder": 1}))
    year = forms.IntegerField(max_value=2016, min_value=2013, widget=forms.NumberInput(attrs={"max": 2016, "min": 2013, "placeholder": 2015}))
    class Meta:
        model = APExam
        fields = ["name",
                  "score",
                  "year",
                  "took_class"]

class SAT2Form(forms.ModelForm):
    score = forms.IntegerField(max_value=800, min_value=200, widget=forms.NumberInput(attrs={"max": 800, "min": 1, "placeholder": 200}))
    year = forms.IntegerField(max_value=2016, min_value=2013, widget=forms.NumberInput(attrs={"max": 2016, "min": 2013, "placeholder": 2015}))

    class Meta:
        model = SAT2
        fields = ["name",
                  "score",
                  "year"]

class SeniorForm(forms.ModelForm):
    gpa = forms.DecimalField(max_value=5.0, min_value=0.0, max_digits=4, decimal_places=3)
    sat2400 = forms.IntegerField(max_value=2400, min_value=0)
    sat1600 = forms.IntegerField(max_value=1600, min_value=0)
    act = forms.IntegerField(max_value=36, min_value=0)
    honors = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(SeniorForm, self).__init__(*args, **kwargs)
        self.fields["email"].label = "Other Email"
        self.fields["email"].help_text = "(Optional)"
        self.fields["gpa"].label = "GPA"
        self.fields["sat2400"].label = "SAT (2400 Scale)"
        self.fields["sat1600"].label = "SAT (1600 Scale)"
        self.fields["act"].label = "ACT"
        for i in ["gpa", "sat2400", "sat1600"]:
            self.fields[i].help_text = "Not required, enter 0"
        self.fields["honors"].label = "Honors/Extracurr's"

    class Meta:
        model = Senior
        fields = ["gender",
                  "email",
                  "race",
                  "hispanic",
                  "international",
                  "gpa",
                  "sat2400",
                  "sat1600",
                  "act",
                  "honors"]

class UserForm(UserCreationForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields["username"].label = "TJ Username"
        self.fields["username"].help_text = "e.x. 2016jwoglom"
        self.fields["password1"].help_text = "Do NOT use your TJHSST password."

    def save(self, commit=True):
        obj = super(UserForm, self).save(commit=False)
        obj.verified = False
        verify_key = str(uuid.uuid4())
        obj.verify_key = verify_key
        if commit:
            obj.save()
        return obj

    class Meta:
        model = User
        fields = ["first_name",
                  "last_name",
                  "username",
                  "password1",
                  "password2",
                  "captcha"]

tjdests/templates/register.html
{% extends "page_base.html" %}

{% block css %}
    {{ block.super }}
    <style type="text/css">
    #id_captcha_1 {
        display: block;
    }
    </style>
{% endblock %}

{% block content %}
    <h2>Register</h2>

    <form action="" method="post" class="register-form">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td colspan="2"><input type="submit" value="Sign Up" /></td>
            </tr>
        </table>
    </form>

{% endblock %}

tjdests/templates/student.html
{% extends "page_base.html" %}

{% block css %}
    {{ block.super }}
    <style type="text/css">
    .student-table {
        width: 100%;
    }

    .college-table {
        font-size: 11px;
    }

    dl dt {
        float: left;
        padding-right: 5px;
        font-weight: bold;
    }

    dl.sat2, dl.aps {
        margin-top: 0;
    }

    table.fancy-table tbody tr .college-table tr {
        background: transparent;
    }

    td.attending {
        background-color: rgba(0,128,0,0.5);
        font-weight: bold;
    }

    td.AC {
        background-color: rgba(0,128,0,0.5);
    }

    td.RJ {
        background-color: rgba(128,0,0,0.5);
    }

    h3 {
        margin: 0;
        text-decoration: underline;
    }
    </style>
{% endblock %}

{% block content %}

    {% with user=student.user %}
        <span class="name">
            <h1>{{ user.first_name }} {{ user.last_name }}</h1>
        </span>
    {% endwith %}
    {% if is_self %}<b>This is you! <a href="{% url 'update' %}">Edit your profile</a></b><br />{% endif %}

    <dl class="info">
        <dt>Gender:</dt>
        <dd>{{ student.gender }}</dd>
        <dt>Race:</dt>
        <dd>{{ student.race }}</dd>
        {% if student.hispanic %}
            <dt>Hispanic</dt>
            <dd>Yes</dd>
        {% endif %}
        {% if student.international %}
            <dt>International</dt>
            <dd>Yes</dd>
        {% endif %}

        {% if student.gpa and student.gpa > 0%}
            <dt>GPA:</dt>
            <dd>{{ student.gpa }}</dd>
        {% endif %}
        {% if student.sat2400 %}
            <dt>SAT 2400:</dt>
            <dd>{{ student.sat2400 }}</dd>
        {% endif %}
        {% if student.sat1600 %}
            <dt>SAT 1600:</dt>
            <dd>{{ student.sat1600 }}</dd>
        {% endif %}
        {% if student.act %}
            <dt>ACT:</dt>
            <dd>{{ student.act }}</dd>
        {% endif %}
    </dl>
    <h3>SAT II:</h3>
    <dl class="sat2">
        {% for t in student.sat2_set.all %}
            <dt>{{ t.name }}:</dt>
            <dd>{{ t.score }} ({{ t.year }})</dd>
        {% empty %}
            <dt>No SAT IIs</dt>
            <dd>&nbsp;</dd>
        {% endfor %}
    </dl>
    <h3>AP Exams:</h3>
    <dl class="aps">
        {% for t in student.apexam_set.all %}
            <dt>{{ t.name }}:</dt>
            <dd{% if t.took_class %} title="Took class"{% endif %}>{{ t.score }} ({{ t.year }})</dd>
        {% empty %}
            <dt>No AP Exams</dt>
            <dd>&nbsp;</dd>
        {% endfor %}
    </dl>
    <h3>Honors/Extracurriculars:</h3>
    <span>{{ student.honors|linebreaksbr }}</span>
    
    <table class="college-table fancy-table">
        <thead>
            <tr>
                <th>Decision</th>
                <th>College</th>
                <th>Program</th>
                <th>App Type</th>
                <th>Submitted</th>
                <th>Notified</th>
                <th>Legacy?</th>
                <th>Interview?</th>
                <th>Deferred?</th>
                <th>Waitlisted?</th>
                <th>Recruited?</th>
                <th>Supplement</th>
                <th>Comments</th>
                {% if is_self %}<th></th>{% endif %}
            </tr>
        </thead>
        <tbody>
            {% for c in student.collegeapp_set.all %}
            <tr>
                {% if c.attending %}
                    <td class="attending"><i class='fa fa-check'></i>Attending</td>
                {% else %}
                    <td class="{{ c.result }}">{{ c.result_name }}</td>
                {% endif %}
                <th><a href="{% url 'college' c.college.ceeb %}">
                    {{ c.college.name }}
                </a></th>
                <td>{{ c.program }}</td>
                <td title="{{ c.applied_name }}">{{ c.applied }}</td>
                <td>{{ c.submitted }}</td>
                <td>{{ c.notified }}</td>
                <td>{{ c.legacy }}</td>
                <td>{{ c.interview }}</td>
                <td>{{ c.deferred }}</td>
                <td>{{ c.waitlisted }}</td>
                <td>{{ c.recruited }}</td>
                <td>{{ c.supplement }}</td>
                <td>{{ c.comments|linebreaksbr }}</td>
                {% if is_self %}
                    <td>
                        <a href="{% url 'update_school' c.id %}" class="button">Update</a>
                    </td>
                {% endif %}
            </tr>
            {% empty %}
            <tr>
                <th colspan="13">No colleges</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

tjdests/templates/students.html
{% extends "page_base.html" %}

{% block css %}
    {{ block.super }}
    <style type="text/css">
    .student-table {
        width: 100%;
        font-size: 12px;
    }

    dl dt {
        float: left;
        padding-right: 5px;
        font-weight: bold;
    }

    dl.sat2ap {
        white-space: nowrap;
    }

    table.fancy-table tbody tr .college-table tr {
        background: transparent;
    }

    table.college-table[data-sortable] th, table.college-table[data-sortable] td {
        padding: 3px;
    }

    tr.AC td {
        background-color: rgba(0,128,0,0.5);
    }

    tr.RJ td {
        background-color: rgba(128,0,0,0.5);
    }
    th.colleges {
        min-width: 300px;
    }
    </style>
{% endblock %}

{% block content %}
    <table class="student-table fancy-table" data-sortable>
    <thead>
        <tr>
            <th>Name</th>
            <th>Info</th>
            <th>Scores</th>
            <th>SAT II/APs</th>
            <th>Honors/Extracurriculars</th>
            <th class="colleges">Colleges</th>
        </tr>
    </thead>
    <tbody>
    {% for student in students %}
        <tr>
            <td>
            {% with user=student.user %}
                <span class="name">
                    <a href="{% url 'student' student.id %}">{{ user.first_name }} {{ user.last_name }}</a>
                    {% if student.email %}
                        <br />
                        {{ student.email }}
                    {% endif %}
                </span>
            {% endwith %}
            </td>
            <td>
                <dl class="info">
                    <dt>Gender:</dt>
                    <dd>{{ student.gender }}</dd>
                    <dt>Race:</dt>
                    <dd>{{ student.race }}</dd>
                    {% if student.hispanic %}
                        <dt>Hispanic</dt>
                        <dd>Yes</dd>
                    {% endif %}
                    {% if student.international %}
                        <dt>International</dt>
                        <dd>Yes</dd>
                    {% endif %}
                </dl>
            </td>
            <td>
                <dl class="scores">
                    {% if student.gpa and student.gpa > 0 %}
                        <dt>GPA:</dt>
                        <dd>{{ student.gpa }}</dd>
                    {% endif %}
                    {% if student.sat2400 %}
                        <dt>SAT 2400:</dt>
                        <dd>{{ student.sat2400 }}</dd>
                    {% endif %}
                    {% if student.sat1600 %}
                        <dt>SAT 1600:</dt>
                        <dd>{{ student.sat1600 }}</dd>
                    {% endif %}
                    {% if student.act %}
                        <dt>ACT:</dt>
                        <dd>{{ student.act }}</dd>
                    {% endif %}
                </dl>
            </td>
            <td>
                <dl class="sat2ap">
                    {% for t in student.sat2_set.all %}
                        <dt>SATII {{ t.name }}:</dt>
                        <dd>{{ t.score }} ({{ t.year }})</dd>
                    {% empty %}
                        <dt>No SAT IIs</dt>
                        <dd>&nbsp;</dd>
                    {% endfor %}

                    {% for t in student.apexam_set.all %}
                        <dt>AP {{ t.name }}:</dt>
                        <dd{% if t.took_class %} title="Took class"{% endif %}>{{ t.score }} ({{ t.year }})</dd>
                    {% empty %}
                        <dt>No AP Exams</dt>
                        <dd>&nbsp;</dd>
                    {% endfor %}
                </dl>
            </td>
            <td>
                {{ student.honors|linebreaksbr }}
            </td>
            <td>
                <table class="college-table" data-sortable="false">
                    {% for c in student.collegeapp_set.all %}
                    <tr data-sortable="false" class="{% if c.attending %}attending AC{% else %}{{ c.result }}{% endif %}">
                        <td data-sortable="false" style="text-align: center">{% if c.attending %}<i class='fa fa-check'></i>{% endif %}{{ c.applied }}</td>
                        <th data-sortable="false">{{ c.college.name }}</th>
                    </tr>
                    {% empty %}
                    <tr>
                        <th colspan="2">No colleges</th>
                    </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

tjdests/templates/update.html
{% extends "page_base.html" %}

{% block css %}
    {{ block.super }}
    <style type="text/css">
    textarea {
        height: 100px;
    }
    </style>
{% endblock %}

{% block content %}
    <h2>{% if senior %}Update{% else %}Add{% endif %} Info</h2>

    {% if updated %}
    <div class="message">
        <i class="fa fa-check"></i> Your information was updated! <a href="{% url 'student' senior.id %}">View your profile</a>
    </div>
    {% endif %}

    {% if senior.collegeapp_set.count == 0 %}
        <b>Start adding schools:</b>
    {% else %}
        Update or add more schools:
    {% endif %}
    <br />
    <a href="{% url 'update_schools' %}" class="button">Update/Add Schools</a>
    
    <br /><br />

    {% if senior.apexam_set.count == 0 %}
        <b>Start adding AP Exams:</b>
    {% else %}
        Update or add more AP Exams:
    {% endif %}
    <br />
    <a href="{% url 'update_apexams' %}" class="button">Update/Add AP Exams</a>

    <br /><br />

    {% if senior.sat2_set.count == 0 %}
        <b>Start adding SAT Subject Tests:</b>
    {% else %}
        Update or add more SAT Subject Tests:
    {% endif %}
    <br />
    <a href="{% url 'update_sat2s' %}" class="button">Update/Add SAT Subject Tests</a>
    

    <h3>Update Personal Info:</h3>

    <form action="" method="post" class="update-form">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td colspan="2"><input type="submit" value="{% if senior %}Update{% else %}Add{% endif %} Info" /></td>
            </tr>
        </table>
    </form>

{% endblock %}

tjdests/templates/update_apexam.html
{% extends "page_base.html" %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'selectize.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'selectize.default.css' %}" />
    <style type="text/css">
    textarea {
        height: 100px;
    }
    </style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'selectize.min.js' %}"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_name").selectize().parent().css({"width": "200px"});

        deleteExam = function() {
            if(!confirm("Are you sure you want to delete this AP exam?")) return;
            $("form.update-form").append("<input type='hidden' name='delete' value=1 />");
            document.forms["form"].submit();
        }
    });
    </script>
{% endblock %}

{% block content %}
    <h2>{% if exam %}Update{% else %}Add{% endif %} AP Exam</h2>

    {% if updated %}
    <div class="message">
        <i class="fa fa-check"></i> Your information was updated! <a href="{% url 'student' senior.id %}">View your profile</a>
    </div>
    {% endif %}

    <a href="/update" class="button">Edit Profile/Edit Schools</a>
    <br /><br />

    <form action="" method="post" class="update-form" name="form">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td colspan="2">
                    <input type="submit" value="{% if exam %}Update{% else %}Add{% endif %} Exam" />
                    {% if app %}
                        <button onclick="deleteExam(); return false">Delete</button>
                    {% endif %}
                </td>
            </tr>
        </table>
    </form>

{% endblock %}

tjdests/templates/update_school.html
{% extends "page_base.html" %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'selectize.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'selectize.default.css' %}" />
    <style type="text/css">
    textarea {
        height: 100px;
    }
    </style>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'selectize.min.js' %}"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_college").selectize().parent().css({"width": "500px"});

        deleteApp = function() {
            if(!confirm("Are you sure you want to delete this college app?")) return;
            $("form.update-form").append("<input type='hidden' name='delete' value=1 />");
            document.forms["form"].submit();
        }

        $("#id_submitted, #id_notified").attr("placeholder", "YYYY-MM-DD or blank")
    });
    </script>
{% endblock %}

{% block content %}
    <h2>{% if app %}Update{% else %}Add{% endif %} School</h2>

    {% if updated %}
    <div class="message">
        <i class="fa fa-check"></i> Your information was updated! <a href="{% url 'student' senior.id %}">View your profile</a>
    </div>
    {% endif %}

    {% if request.GET.deleted %}
    <div class="message">
        The college application was deleted. <a href="{% url 'student' senior.id %}">View your profile</a>
    </div>
    {% endif %}

    <a href="/update" class="button">Edit Profile/Edit Schools</a>
    <br /><br />

    <form action="" method="post" class="update-form" name="form">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td colspan="2">
                    <input type="submit" value="{% if app %}Update{% else %}Add{% endif %} Info" />
                    {% if app %}
                        <button onclick="deleteApp(); return false">Delete</button>
                    {% endif %}
                </td>
            </tr>
        </table>
    </form>

{% endblock %}